[phases.setup]
nixPkgs = [
  'python311',
  'libGL',
  'libglib',
  'glib',
  'libSM',
  'libXext',
  'libXrender',
  'libgomp',
  'libglvnd',
  'mesa',
  'pkg-config'
]

[phases.install]
cmds = [
  'cd webapp',
  'pip install --upgrade pip',
  'pip install --no-cache-dir opencv-python-headless==4.8.1.78',
  'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]  
cmds = ['echo "Build complete"']

[start]
cmd = 'cd webapp && python app.py' 