[phases.setup]
nixPkgs = [
  'python311',
  'libGL',
  'libglib',
  'xorg.libSM',
  'xorg.libXext',
  'xorg.libXrender',
  'libgomp',
  'mesa',
  'pkg-config'
]

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install --no-cache-dir opencv-python-headless==4.8.1.78',
  'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]  
cmds = ['echo "Build complete"']

[start]
cmd = 'python app.py' 